all: Structure.class

%.class: %.java
	javac  -classpath ./:./cdk-1.3.5.jar:./cdk-jchempaint-15.jar $<
	#javac -classpath ./:./cdk-1.2.5.jar $<
	#javac -Xlint:deprecation -Xlint:unchecked -classpath ./:./cdk-1.3.5.jar:./cdk-jchempaint-15.jar $<
